---
- name: Load OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}.yml"
    - "../vars/default.yml"
  tags: [always]

- import_tasks: _install.yml
  tags: [barman, barman-install]

- import_tasks: _configure.yml
  tags: [barman, barman-configure]

- import_tasks: _cron.yml
  tags: [barman, barman-cron]
