---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution_release }}.yml"
    - "../vars/default.yml"
  tags: [always]

- include: install.yml
  tags: [barman, barman-install]

- include: configure.yml
  tags: [barman, barman-configure]

- include: cron.yml
  tags: [barman, barman-cron]
